server.port=8081

spring.application.name=halconGym

spring.datasource.url=jdbc:mysql://localhost:3306/halconGym?createDatabaseIfNotExist=true
# spring.datasource.username=root
# spring.datasource.password=chuflitos1

# Estas credenciales habilitarlas cuando se vaya a subir al servidor
spring.datasource.username=gymuser
spring.datasource.password=Gym1234!

##Configuración de MYSQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

##Manera de crear las tablas
spring.jpa.hibernate.ddl-auto=update
# spring.jpa.hibernate.ddl-auto=validate
# spring.jpa.hibernate.ddl-auto=create
# spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

gym.logo=/img/halcongympng.png

# Envio de MSJ automáticos:
# evolution.api.url=http://66.97.36.196:3000
# No cambiar la api.key, es la GLOBAL del servidor (levantado con docker-compose en el servidor), solo cambiar instance según gym
# evolution.api.key=CAPTAIN_GYM_SECRET
# Cambiar la instancia segun el que vaya a usar:
# evolution.instance=pruebagym3
# captain-gym   es la que está funcionando ahora mismo

# Para crear nuevas instancias, ingresar a http://66.97.36.196:3000/manager
#  va a pedir api.key y pones CAPTAIN_GYM_SECRET, luego de eso crear instancia, escanear el qr con el whatsapp del gym y listo

# Tiempo en vida de la sesión:
server.servlet.session.timeout=8h
